/* Generated by re2c 2.0.3 on Fri Jun 11 00:46:34 2021 */
// A Bison parser, made by GNU Bison 3.4.1.

// Skeleton implementation for Bison LALR(1) parsers in C++

// Copyright (C) 2002-2015, 2018-2019 Free Software Foundation, Inc.

// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.

// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

// As a special exception, you may create a larger work that contains
// part or all of the Bison parser skeleton and distribute that work
// under terms of your choice, so long as that work isn't itself a
// parser generator using the skeleton or a modified version thereof
// as a parser skeleton.  Alternatively, if you modify or redistribute
// the parser skeleton itself, you may (at your option) remove this
// special exception, which will cause the skeleton and the resulting
// Bison output files to be licensed under the GNU General Public
// License without this special exception.

// This special exception was added by the Free Software Foundation in
// version 2.2 of Bison.

// Undocumented macros, especially those whose name start with YY_,
// are private implementation details.  Do not rely on them.





#include "compiler.tab.hpp"


// Unqualified %code blocks.

#include "compiler.hpp"



#ifndef YY_
# if defined YYENABLE_NLS && YYENABLE_NLS
#  if ENABLE_NLS
#   include <libintl.h> // FIXME: INFRINGES ON USER NAME SPACE.
#   define YY_(msgid) dgettext ("bison-runtime", msgid)
#  endif
# endif
# ifndef YY_
#  define YY_(msgid) msgid
# endif
#endif

// Whether we are compiled with exception support.
#ifndef YY_EXCEPTIONS
# if defined __GNUC__ && !defined __EXCEPTIONS
#  define YY_EXCEPTIONS 0
# else
#  define YY_EXCEPTIONS 1
# endif
#endif

#define YYRHSLOC(Rhs, K) ((Rhs)[K].location)
/* YYLLOC_DEFAULT -- Set CURRENT to span from RHS[1] to RHS[N].
   If N is 0, then set CURRENT to the empty location which ends
   the previous symbol: RHS[0] (always defined).  */

# ifndef YYLLOC_DEFAULT
#  define YYLLOC_DEFAULT(Current, Rhs, N)                               \
    do                                                                  \
      if (N)                                                            \
        {                                                               \
          (Current).begin  = YYRHSLOC (Rhs, 1).begin;                   \
          (Current).end    = YYRHSLOC (Rhs, N).end;                     \
        }                                                               \
      else                                                              \
        {                                                               \
          (Current).begin = (Current).end = YYRHSLOC (Rhs, 0).end;      \
        }                                                               \
    while (false)
# endif


// Suppress unused-variable warnings by "using" E.
#define YYUSE(E) ((void) (E))

// Enable debugging if requested.
#if YYDEBUG

// A pseudo ostream that takes yydebug_ into account.
# define YYCDEBUG if (yydebug_) (*yycdebug_)

# define YY_SYMBOL_PRINT(Title, Symbol)         \
  do {                                          \
    if (yydebug_)                               \
    {                                           \
      *yycdebug_ << Title << ' ';               \
      yy_print_ (*yycdebug_, Symbol);           \
      *yycdebug_ << '\n';                       \
    }                                           \
  } while (false)

# define YY_REDUCE_PRINT(Rule)          \
  do {                                  \
    if (yydebug_)                       \
      yy_reduce_print_ (Rule);          \
  } while (false)

# define YY_STACK_PRINT()               \
  do {                                  \
    if (yydebug_)                       \
      yystack_print_ ();                \
  } while (false)

#else // !YYDEBUG

# define YYCDEBUG if (false) std::cerr
# define YY_SYMBOL_PRINT(Title, Symbol)  YYUSE (Symbol)
# define YY_REDUCE_PRINT(Rule)           static_cast<void> (0)
# define YY_STACK_PRINT()                static_cast<void> (0)

#endif // !YYDEBUG

#define yyerrok         (yyerrstatus_ = 0)
#define yyclearin       (yyla.clear ())

#define YYACCEPT        goto yyacceptlab
#define YYABORT         goto yyabortlab
#define YYERROR         goto yyerrorlab
#define YYRECOVERING()  (!!yyerrstatus_)

namespace  cyy  {


  /* Return YYSTR after stripping away unnecessary quotes and
     backslashes, so that it's suitable for yyerror.  The heuristic is
     that double-quoting is unnecessary unless the string contains an
     apostrophe, a comma, or backslash (other than backslash-backslash).
     YYSTR is taken from yytname.  */
  std::string
  parser::yytnamerr_ (const char *yystr)
  {
    if (*yystr == '"')
      {
        std::string yyr;
        char const *yyp = yystr;

        for (;;)
          switch (*++yyp)
            {
            case '\'':
            case ',':
              goto do_not_strip_quotes;

            case '\\':
              if (*++yyp != '\\')
                goto do_not_strip_quotes;
              else
                goto append;

            append:
            default:
              yyr += *yyp;
              break;

            case '"':
              return yyr;
            }
      do_not_strip_quotes: ;
      }

    return yystr;
  }


  /// Build a parser object.
  parser::parser (kasm::Compiler& compiler_yyarg)
    :
#if YYDEBUG
      yydebug_ (false),
      yycdebug_ (&std::cerr),
#endif
      compiler (compiler_yyarg)
  {}

  parser::~parser ()
  {}

  parser::syntax_error::~syntax_error () YY_NOEXCEPT YY_NOTHROW
  {}

  /*---------------.
  | Symbol types.  |
  `---------------*/



  // by_state.
  parser::by_state::by_state () YY_NOEXCEPT
    : state (empty_state)
  {}

  parser::by_state::by_state (const by_state& that) YY_NOEXCEPT
    : state (that.state)
  {}

  void
  parser::by_state::clear () YY_NOEXCEPT
  {
    state = empty_state;
  }

  void
  parser::by_state::move (by_state& that)
  {
    state = that.state;
    that.clear ();
  }

  parser::by_state::by_state (state_type s) YY_NOEXCEPT
    : state (s)
  {}

  parser::symbol_number_type
  parser::by_state::type_get () const YY_NOEXCEPT
  {
    if (state == empty_state)
      return empty_symbol;
    else
      return yystos_[state];
  }

  parser::stack_symbol_type::stack_symbol_type ()
  {}

  parser::stack_symbol_type::stack_symbol_type (YY_RVREF (stack_symbol_type) that)
    : super_type (YY_MOVE (that.state), YY_MOVE (that.location))
  {
    switch (that.type_get ())
    {
      case 36: // statement
      case 39: // compound_statement
      case 40: // expression
      case 41: // expression_or_nothing
      case 42: // function_definition
      case 43: // type
      case 44: // identifier
      case 45: // literal
      case 46: // string_literal
        value.YY_MOVE_OR_COPY< kasm::ast::Node* > (YY_MOVE (that.value));
        break;

      case 17: // TYPE
        value.YY_MOVE_OR_COPY< kasm::ast::Type > (YY_MOVE (that.value));
        break;

      case 14: // IDENTIFIER
      case 15: // STRING
        value.YY_MOVE_OR_COPY< std::string > (YY_MOVE (that.value));
        break;

      case 16: // LITERAL
        value.YY_MOVE_OR_COPY< std::uint32_t > (YY_MOVE (that.value));
        break;

      default:
        break;
    }

#if 201103L <= YY_CPLUSPLUS
    // that is emptied.
    that.state = empty_state;
#endif
  }

  parser::stack_symbol_type::stack_symbol_type (state_type s, YY_MOVE_REF (symbol_type) that)
    : super_type (s, YY_MOVE (that.location))
  {
    switch (that.type_get ())
    {
      case 36: // statement
      case 39: // compound_statement
      case 40: // expression
      case 41: // expression_or_nothing
      case 42: // function_definition
      case 43: // type
      case 44: // identifier
      case 45: // literal
      case 46: // string_literal
        value.move< kasm::ast::Node* > (YY_MOVE (that.value));
        break;

      case 17: // TYPE
        value.move< kasm::ast::Type > (YY_MOVE (that.value));
        break;

      case 14: // IDENTIFIER
      case 15: // STRING
        value.move< std::string > (YY_MOVE (that.value));
        break;

      case 16: // LITERAL
        value.move< std::uint32_t > (YY_MOVE (that.value));
        break;

      default:
        break;
    }

    // that is emptied.
    that.type = empty_symbol;
  }

#if YY_CPLUSPLUS < 201103L
  parser::stack_symbol_type&
  parser::stack_symbol_type::operator= (stack_symbol_type& that)
  {
    state = that.state;
    switch (that.type_get ())
    {
      case 36: // statement
      case 39: // compound_statement
      case 40: // expression
      case 41: // expression_or_nothing
      case 42: // function_definition
      case 43: // type
      case 44: // identifier
      case 45: // literal
      case 46: // string_literal
        value.move< kasm::ast::Node* > (that.value);
        break;

      case 17: // TYPE
        value.move< kasm::ast::Type > (that.value);
        break;

      case 14: // IDENTIFIER
      case 15: // STRING
        value.move< std::string > (that.value);
        break;

      case 16: // LITERAL
        value.move< std::uint32_t > (that.value);
        break;

      default:
        break;
    }

    location = that.location;
    // that is emptied.
    that.state = empty_state;
    return *this;
  }
#endif

  template <typename Base>
  void
  parser::yy_destroy_ (const char* yymsg, basic_symbol<Base>& yysym) const
  {
    if (yymsg)
      YY_SYMBOL_PRINT (yymsg, yysym);
  }

#if YYDEBUG
  template <typename Base>
  void
  parser::yy_print_ (std::ostream& yyo,
                                     const basic_symbol<Base>& yysym) const
  {
    std::ostream& yyoutput = yyo;
    YYUSE (yyoutput);
    symbol_number_type yytype = yysym.type_get ();
#if defined __GNUC__ && ! defined __clang__ && ! defined __ICC && __GNUC__ * 100 + __GNUC_MINOR__ <= 408
    // Avoid a (spurious) G++ 4.8 warning about "array subscript is
    // below array bounds".
    if (yysym.empty ())
      std::abort ();
#endif
    yyo << (yytype < yyntokens_ ? "token" : "nterm")
        << ' ' << yytname_[yytype] << " ("
        << yysym.location << ": ";
    YYUSE (yytype);
    yyo << ')';
  }
#endif

  void
  parser::yypush_ (const char* m, YY_MOVE_REF (stack_symbol_type) sym)
  {
    if (m)
      YY_SYMBOL_PRINT (m, sym);
    yystack_.push (YY_MOVE (sym));
  }

  void
  parser::yypush_ (const char* m, state_type s, YY_MOVE_REF (symbol_type) sym)
  {
#if 201103L <= YY_CPLUSPLUS
    yypush_ (m, stack_symbol_type (s, std::move (sym)));
#else
    stack_symbol_type ss (s, sym);
    yypush_ (m, ss);
#endif
  }

  void
  parser::yypop_ (int n)
  {
    yystack_.pop (n);
  }

#if YYDEBUG
  std::ostream&
  parser::debug_stream () const
  {
    return *yycdebug_;
  }

  void
  parser::set_debug_stream (std::ostream& o)
  {
    yycdebug_ = &o;
  }


  parser::debug_level_type
  parser::debug_level () const
  {
    return yydebug_;
  }

  void
  parser::set_debug_level (debug_level_type l)
  {
    yydebug_ = l;
  }
#endif // YYDEBUG

  parser::state_type
  parser::yy_lr_goto_state_ (state_type yystate, int yysym)
  {
    int yyr = yypgoto_[yysym - yyntokens_] + yystate;
    if (0 <= yyr && yyr <= yylast_ && yycheck_[yyr] == yystate)
      return yytable_[yyr];
    else
      return yydefgoto_[yysym - yyntokens_];
  }

  bool
  parser::yy_pact_value_is_default_ (int yyvalue)
  {
    return yyvalue == yypact_ninf_;
  }

  bool
  parser::yy_table_value_is_error_ (int yyvalue)
  {
    return yyvalue == yytable_ninf_;
  }

  int
  parser::operator() ()
  {
    return parse ();
  }

  int
  parser::parse ()
  {
    // State.
    int yyn;
    /// Length of the RHS of the rule being reduced.
    int yylen = 0;

    // Error handling.
    int yynerrs_ = 0;
    int yyerrstatus_ = 0;

    /// The lookahead symbol.
    symbol_type yyla;

    /// The locations where the error started and ended.
    stack_symbol_type yyerror_range[3];

    /// The return value of parse ().
    int yyresult;

#if YY_EXCEPTIONS
    try
#endif // YY_EXCEPTIONS
      {
    YYCDEBUG << "Starting parse\n";


    /* Initialize the stack.  The initial state will be set in
       yynewstate, since the latter expects the semantical and the
       location values to have been already stored, initialize these
       stacks with a primary value.  */
    yystack_.clear ();
    yypush_ (YY_NULLPTR, 0, YY_MOVE (yyla));

  /*-----------------------------------------------.
  | yynewstate -- push a new symbol on the stack.  |
  `-----------------------------------------------*/
  yynewstate:
    YYCDEBUG << "Entering state " << yystack_[0].state << '\n';

    // Accept?
    if (yystack_[0].state == yyfinal_)
      YYACCEPT;

    goto yybackup;


  /*-----------.
  | yybackup.  |
  `-----------*/
  yybackup:
    // Try to take a decision without lookahead.
    yyn = yypact_[yystack_[0].state];
    if (yy_pact_value_is_default_ (yyn))
      goto yydefault;

    // Read a lookahead token.
    if (yyla.empty ())
      {
        YYCDEBUG << "Reading a token: ";
#if YY_EXCEPTIONS
        try
#endif // YY_EXCEPTIONS
          {
            symbol_type yylookahead (yylex (compiler));
            yyla.move (yylookahead);
          }
#if YY_EXCEPTIONS
        catch (const syntax_error& yyexc)
          {
            YYCDEBUG << "Caught exception: " << yyexc.what() << '\n';
            error (yyexc);
            goto yyerrlab1;
          }
#endif // YY_EXCEPTIONS
      }
    YY_SYMBOL_PRINT ("Next token is", yyla);

    /* If the proper action on seeing token YYLA.TYPE is to reduce or
       to detect an error, take that action.  */
    yyn += yyla.type_get ();
    if (yyn < 0 || yylast_ < yyn || yycheck_[yyn] != yyla.type_get ())
      goto yydefault;

    // Reduce or error.
    yyn = yytable_[yyn];
    if (yyn <= 0)
      {
        if (yy_table_value_is_error_ (yyn))
          goto yyerrlab;
        yyn = -yyn;
        goto yyreduce;
      }

    // Count tokens shifted since error; after three, turn off error status.
    if (yyerrstatus_)
      --yyerrstatus_;

    // Shift the lookahead token.
    yypush_ ("Shifting", yyn, YY_MOVE (yyla));
    goto yynewstate;


  /*-----------------------------------------------------------.
  | yydefault -- do the default action for the current state.  |
  `-----------------------------------------------------------*/
  yydefault:
    yyn = yydefact_[yystack_[0].state];
    if (yyn == 0)
      goto yyerrlab;
    goto yyreduce;


  /*-----------------------------.
  | yyreduce -- do a reduction.  |
  `-----------------------------*/
  yyreduce:
    yylen = yyr2_[yyn];
    {
      stack_symbol_type yylhs;
      yylhs.state = yy_lr_goto_state_ (yystack_[yylen].state, yyr1_[yyn]);
      /* Variants are always initialized to an empty instance of the
         correct type. The default '$$ = $1' action is NOT applied
         when using variants.  */
      switch (yyr1_[yyn])
    {
      case 36: // statement
      case 39: // compound_statement
      case 40: // expression
      case 41: // expression_or_nothing
      case 42: // function_definition
      case 43: // type
      case 44: // identifier
      case 45: // literal
      case 46: // string_literal
        yylhs.value.emplace< kasm::ast::Node* > ();
        break;

      case 17: // TYPE
        yylhs.value.emplace< kasm::ast::Type > ();
        break;

      case 14: // IDENTIFIER
      case 15: // STRING
        yylhs.value.emplace< std::string > ();
        break;

      case 16: // LITERAL
        yylhs.value.emplace< std::uint32_t > ();
        break;

      default:
        break;
    }


      // Default location.
      {
        stack_type::slice range (yystack_, yylen);
        YYLLOC_DEFAULT (yylhs.location, range, yylen);
        yyerror_range[1].location = yylhs.location;
      }

      // Perform the reduction.
      YY_REDUCE_PRINT (yyn);
#if YY_EXCEPTIONS
      try
#endif // YY_EXCEPTIONS
        {
          switch (yyn)
            {
  case 2:
    { compiler.astRoot = kasm::ast::makeEmpty(); }
    break;

  case 3:
    { compiler.astRoot = kasm::ast::makeCompound(compiler.astRoot, yystack_[0].value.as < kasm::ast::Node* > ()); }
    break;

  case 4:
    { compiler.astRoot = kasm::ast::makeCompound(compiler.astRoot, yystack_[0].value.as < kasm::ast::Node* > ()); }
    break;

  case 5:
    { yylhs.value.as < kasm::ast::Node* > () = kasm::ast::makeEmpty(); }
    break;

  case 6:
    { yylhs.value.as < kasm::ast::Node* > () = yystack_[1].value.as < kasm::ast::Node* > (); }
    break;

  case 7:
    { yylhs.value.as < kasm::ast::Node* > () = kasm::ast::makeReturn(yystack_[1].value.as < kasm::ast::Node* > ()); }
    break;

  case 8:
    { compiler.parseFlag = kasm::Compiler::ParseFlag::BLOCK_AS_STRING; }
    break;

  case 9:
    {compiler.parseFlag = kasm::Compiler::ParseFlag::NONE;}
    break;

  case 10:
    { yylhs.value.as < kasm::ast::Node* > () = kasm::ast::makeASM(yystack_[2].value.as < std::string > ()); }
    break;

  case 11:
    { yylhs.value.as < kasm::ast::Node* > () = yystack_[1].value.as < kasm::ast::Node* > (); }
    break;

  case 12:
    { yylhs.value.as < kasm::ast::Node* > () = kasm::ast::makeIfThen(yystack_[2].value.as < kasm::ast::Node* > (), yystack_[0].value.as < kasm::ast::Node* > ()); }
    break;

  case 13:
    { yylhs.value.as < kasm::ast::Node* > () = kasm::ast::makeIfThenElse(yystack_[4].value.as < kasm::ast::Node* > (), yystack_[2].value.as < kasm::ast::Node* > (), yystack_[0].value.as < kasm::ast::Node* > ()); }
    break;

  case 14:
    { yylhs.value.as < kasm::ast::Node* > () = kasm::ast::makeWhile(yystack_[2].value.as < kasm::ast::Node* > (), yystack_[0].value.as < kasm::ast::Node* > ()); }
    break;

  case 15:
    { yylhs.value.as < kasm::ast::Node* > () = kasm::ast::makeFor(yystack_[6].value.as < kasm::ast::Node* > (), yystack_[4].value.as < kasm::ast::Node* > (), yystack_[2].value.as < kasm::ast::Node* > (), yystack_[0].value.as < kasm::ast::Node* > ()); }
    break;

  case 16:
    { yylhs.value.as < kasm::ast::Node* > () = kasm::ast::makeDoWhile(yystack_[2].value.as < kasm::ast::Node* > (), yystack_[5].value.as < kasm::ast::Node* > ()); }
    break;

  case 17:
    { yylhs.value.as < kasm::ast::Node* > () = kasm::ast::makeEmpty(); }
    break;

  case 18:
    { yylhs.value.as < kasm::ast::Node* > () = kasm::ast::makeCompound(yystack_[1].value.as < kasm::ast::Node* > (), yystack_[0].value.as < kasm::ast::Node* > ()); }
    break;

  case 19:
    { yylhs.value.as < kasm::ast::Node* > () = kasm::ast::makeBinaryOperator(kasm::ast::BinaryOperator::ADD, yystack_[2].value.as < kasm::ast::Node* > (), yystack_[0].value.as < kasm::ast::Node* > ()); }
    break;

  case 20:
    { yylhs.value.as < kasm::ast::Node* > () = kasm::ast::makeBinaryOperator(kasm::ast::BinaryOperator::MODULUS, yystack_[2].value.as < kasm::ast::Node* > (), yystack_[0].value.as < kasm::ast::Node* > ()); }
    break;

  case 21:
    { yylhs.value.as < kasm::ast::Node* > () = kasm::ast::makeBinaryOperator(kasm::ast::BinaryOperator::ASSIGNMENT, yystack_[2].value.as < kasm::ast::Node* > (), yystack_[0].value.as < kasm::ast::Node* > ()); }
    break;

  case 22:
    { yylhs.value.as < kasm::ast::Node* > () = kasm::ast::makeFunctionCall(yystack_[3].value.as < kasm::ast::Node* > (), yystack_[1].value.as < kasm::ast::Node* > ()); }
    break;

  case 23:
    { yylhs.value.as < kasm::ast::Node* > () = yystack_[1].value.as < kasm::ast::Node* > (); }
    break;

  case 24:
    { yylhs.value.as < kasm::ast::Node* > () = kasm::ast::makeCompound(yystack_[2].value.as < kasm::ast::Node* > (), yystack_[0].value.as < kasm::ast::Node* > ()); }
    break;

  case 25:
    { yylhs.value.as < kasm::ast::Node* > () = kasm::ast::makeVariableDeclaration(yystack_[2].value.as < kasm::ast::Node* > (), yystack_[0].value.as < kasm::ast::Node* > ()); }
    break;

  case 26:
    { yylhs.value.as < kasm::ast::Node* > () = kasm::ast::makeBinaryOperator(kasm::ast::BinaryOperator::EQUAL, yystack_[2].value.as < kasm::ast::Node* > (), yystack_[0].value.as < kasm::ast::Node* > ()); }
    break;

  case 27:
    { yylhs.value.as < kasm::ast::Node* > () = kasm::ast::makeBinaryOperator(kasm::ast::BinaryOperator::LESS_THAN_OR_EQUAL, yystack_[2].value.as < kasm::ast::Node* > (), yystack_[0].value.as < kasm::ast::Node* > ()); }
    break;

  case 28:
    { yylhs.value.as < kasm::ast::Node* > () = kasm::ast::makeBinaryOperator(kasm::ast::BinaryOperator::LOGICAL_AND, yystack_[2].value.as < kasm::ast::Node* > (), yystack_[0].value.as < kasm::ast::Node* > ()); }
    break;

  case 29:
    { yylhs.value.as < kasm::ast::Node* > () = kasm::ast::makeUnaryOperator(kasm::ast::UnaryOperator::ADDRESS_OF, yystack_[0].value.as < kasm::ast::Node* > ()); }
    break;

  case 30:
    { yylhs.value.as < kasm::ast::Node* > () = kasm::ast::makeUnaryOperator(kasm::ast::UnaryOperator::INDIRECTION, yystack_[0].value.as < kasm::ast::Node* > ()); }
    break;

  case 31:
    { yylhs.value.as < kasm::ast::Node* > () = yystack_[0].value.as < kasm::ast::Node* > (); }
    break;

  case 32:
    { yylhs.value.as < kasm::ast::Node* > () = yystack_[0].value.as < kasm::ast::Node* > (); }
    break;

  case 33:
    { yylhs.value.as < kasm::ast::Node* > () = yystack_[0].value.as < kasm::ast::Node* > (); }
    break;

  case 34:
    { yylhs.value.as < kasm::ast::Node* > () = kasm::ast::makeEmpty(); }
    break;

  case 35:
    { yylhs.value.as < kasm::ast::Node* > () = yystack_[0].value.as < kasm::ast::Node* > (); }
    break;

  case 36:
    { yylhs.value.as < kasm::ast::Node* > () = kasm::ast::makeFunctionDefinition(yystack_[8].value.as < kasm::ast::Node* > (), yystack_[3].value.as < kasm::ast::Node* > (), yystack_[6].value.as < kasm::ast::Node* > (), yystack_[1].value.as < kasm::ast::Node* > ()); }
    break;

  case 37:
    { yylhs.value.as < kasm::ast::Node* > () = kasm::ast::makeType(yystack_[0].value.as < kasm::ast::Type > ()); }
    break;

  case 38:
    { yylhs.value.as < kasm::ast::Node* > () = kasm::ast::makeIdentifier(yystack_[0].value.as < std::string > ()); }
    break;

  case 39:
    { yylhs.value.as < kasm::ast::Node* > () = kasm::ast::makeLiteral(yystack_[0].value.as < std::uint32_t > ()); }
    break;

  case 40:
    { yylhs.value.as < kasm::ast::Node* > () = kasm::ast::makeStringLiteral(yystack_[0].value.as < std::string > ()); }
    break;



            default:
              break;
            }
        }
#if YY_EXCEPTIONS
      catch (const syntax_error& yyexc)
        {
          YYCDEBUG << "Caught exception: " << yyexc.what() << '\n';
          error (yyexc);
          YYERROR;
        }
#endif // YY_EXCEPTIONS
      YY_SYMBOL_PRINT ("-> $$ =", yylhs);
      yypop_ (yylen);
      yylen = 0;
      YY_STACK_PRINT ();

      // Shift the result of the reduction.
      yypush_ (YY_NULLPTR, YY_MOVE (yylhs));
    }
    goto yynewstate;


  /*--------------------------------------.
  | yyerrlab -- here on detecting error.  |
  `--------------------------------------*/
  yyerrlab:
    // If not already recovering from an error, report this error.
    if (!yyerrstatus_)
      {
        ++yynerrs_;
        error (yyla.location, yysyntax_error_ (yystack_[0].state, yyla));
      }


    yyerror_range[1].location = yyla.location;
    if (yyerrstatus_ == 3)
      {
        /* If just tried and failed to reuse lookahead token after an
           error, discard it.  */

        // Return failure if at end of input.
        if (yyla.type_get () == yyeof_)
          YYABORT;
        else if (!yyla.empty ())
          {
            yy_destroy_ ("Error: discarding", yyla);
            yyla.clear ();
          }
      }

    // Else will try to reuse lookahead token after shifting the error token.
    goto yyerrlab1;


  /*---------------------------------------------------.
  | yyerrorlab -- error raised explicitly by YYERROR.  |
  `---------------------------------------------------*/
  yyerrorlab:
    /* Pacify compilers when the user code never invokes YYERROR and
       the label yyerrorlab therefore never appears in user code.  */
    if (false)
      YYERROR;

    /* Do not reclaim the symbols of the rule whose action triggered
       this YYERROR.  */
    yypop_ (yylen);
    yylen = 0;
    goto yyerrlab1;


  /*-------------------------------------------------------------.
  | yyerrlab1 -- common code for both syntax error and YYERROR.  |
  `-------------------------------------------------------------*/
  yyerrlab1:
    yyerrstatus_ = 3;   // Each real token shifted decrements this.
    {
      stack_symbol_type error_token;
      for (;;)
        {
          yyn = yypact_[yystack_[0].state];
          if (!yy_pact_value_is_default_ (yyn))
            {
              yyn += yyterror_;
              if (0 <= yyn && yyn <= yylast_ && yycheck_[yyn] == yyterror_)
                {
                  yyn = yytable_[yyn];
                  if (0 < yyn)
                    break;
                }
            }

          // Pop the current state because it cannot handle the error token.
          if (yystack_.size () == 1)
            YYABORT;

          yyerror_range[1].location = yystack_[0].location;
          yy_destroy_ ("Error: popping", yystack_[0]);
          yypop_ ();
          YY_STACK_PRINT ();
        }

      yyerror_range[2].location = yyla.location;
      YYLLOC_DEFAULT (error_token.location, yyerror_range, 2);

      // Shift the error token.
      error_token.state = yyn;
      yypush_ ("Shifting", YY_MOVE (error_token));
    }
    goto yynewstate;


  /*-------------------------------------.
  | yyacceptlab -- YYACCEPT comes here.  |
  `-------------------------------------*/
  yyacceptlab:
    yyresult = 0;
    goto yyreturn;


  /*-----------------------------------.
  | yyabortlab -- YYABORT comes here.  |
  `-----------------------------------*/
  yyabortlab:
    yyresult = 1;
    goto yyreturn;


  /*-----------------------------------------------------.
  | yyreturn -- parsing is finished, return the result.  |
  `-----------------------------------------------------*/
  yyreturn:
    if (!yyla.empty ())
      yy_destroy_ ("Cleanup: discarding lookahead", yyla);

    /* Do not reclaim the symbols of the rule whose action triggered
       this YYABORT or YYACCEPT.  */
    yypop_ (yylen);
    while (1 < yystack_.size ())
      {
        yy_destroy_ ("Cleanup: popping", yystack_[0]);
        yypop_ ();
      }

    return yyresult;
  }
#if YY_EXCEPTIONS
    catch (...)
      {
        YYCDEBUG << "Exception caught: cleaning lookahead and stack\n";
        // Do not try to display the values of the reclaimed symbols,
        // as their printers might throw an exception.
        if (!yyla.empty ())
          yy_destroy_ (YY_NULLPTR, yyla);

        while (1 < yystack_.size ())
          {
            yy_destroy_ (YY_NULLPTR, yystack_[0]);
            yypop_ ();
          }
        throw;
      }
#endif // YY_EXCEPTIONS
  }

  void
  parser::error (const syntax_error& yyexc)
  {
    error (yyexc.location, yyexc.what ());
  }

  // Generate an error message.
  std::string
  parser::yysyntax_error_ (state_type yystate, const symbol_type& yyla) const
  {
    // Number of reported tokens (one for the "unexpected", one per
    // "expected").
    size_t yycount = 0;
    // Its maximum.
    enum { YYERROR_VERBOSE_ARGS_MAXIMUM = 5 };
    // Arguments of yyformat.
    char const *yyarg[YYERROR_VERBOSE_ARGS_MAXIMUM];

    /* There are many possibilities here to consider:
       - If this state is a consistent state with a default action, then
         the only way this function was invoked is if the default action
         is an error action.  In that case, don't check for expected
         tokens because there are none.
       - The only way there can be no lookahead present (in yyla) is
         if this state is a consistent state with a default action.
         Thus, detecting the absence of a lookahead is sufficient to
         determine that there is no unexpected or expected token to
         report.  In that case, just report a simple "syntax error".
       - Don't assume there isn't a lookahead just because this state is
         a consistent state with a default action.  There might have
         been a previous inconsistent state, consistent state with a
         non-default action, or user semantic action that manipulated
         yyla.  (However, yyla is currently not documented for users.)
       - Of course, the expected token list depends on states to have
         correct lookahead information, and it depends on the parser not
         to perform extra reductions after fetching a lookahead from the
         scanner and before detecting a syntax error.  Thus, state
         merging (from LALR or IELR) and default reductions corrupt the
         expected token list.  However, the list is correct for
         canonical LR with one exception: it will still contain any
         token that will not be accepted due to an error action in a
         later state.
    */
    if (!yyla.empty ())
      {
        int yytoken = yyla.type_get ();
        yyarg[yycount++] = yytname_[yytoken];
        int yyn = yypact_[yystate];
        if (!yy_pact_value_is_default_ (yyn))
          {
            /* Start YYX at -YYN if negative to avoid negative indexes in
               YYCHECK.  In other words, skip the first -YYN actions for
               this state because they are default actions.  */
            int yyxbegin = yyn < 0 ? -yyn : 0;
            // Stay within bounds of both yycheck and yytname.
            int yychecklim = yylast_ - yyn + 1;
            int yyxend = yychecklim < yyntokens_ ? yychecklim : yyntokens_;
            for (int yyx = yyxbegin; yyx < yyxend; ++yyx)
              if (yycheck_[yyx + yyn] == yyx && yyx != yyterror_
                  && !yy_table_value_is_error_ (yytable_[yyx + yyn]))
                {
                  if (yycount == YYERROR_VERBOSE_ARGS_MAXIMUM)
                    {
                      yycount = 1;
                      break;
                    }
                  else
                    yyarg[yycount++] = yytname_[yyx];
                }
          }
      }

    char const* yyformat = YY_NULLPTR;
    switch (yycount)
      {
#define YYCASE_(N, S)                         \
        case N:                               \
          yyformat = S;                       \
        break
      default: // Avoid compiler warnings.
        YYCASE_ (0, YY_("syntax error"));
        YYCASE_ (1, YY_("syntax error, unexpected %s"));
        YYCASE_ (2, YY_("syntax error, unexpected %s, expecting %s"));
        YYCASE_ (3, YY_("syntax error, unexpected %s, expecting %s or %s"));
        YYCASE_ (4, YY_("syntax error, unexpected %s, expecting %s or %s or %s"));
        YYCASE_ (5, YY_("syntax error, unexpected %s, expecting %s or %s or %s or %s"));
#undef YYCASE_
      }

    std::string yyres;
    // Argument number.
    size_t yyi = 0;
    for (char const* yyp = yyformat; *yyp; ++yyp)
      if (yyp[0] == '%' && yyp[1] == 's' && yyi < yycount)
        {
          yyres += yytnamerr_ (yyarg[yyi++]);
          ++yyp;
        }
      else
        yyres += *yyp;
    return yyres;
  }


  const signed char parser::yypact_ninf_ = -40;

  const signed char parser::yytable_ninf_ = -1;

  const short
  parser::yypact_[] =
  {
     -40,    44,   -40,   148,   -27,   -25,   -17,   -10,   141,   -40,
     -40,   -40,   -40,   -40,   148,   148,   148,   -40,   208,   -40,
     -18,   -40,   -40,   219,   -12,   -40,   148,   148,   148,    15,
      79,   164,   230,   230,   148,   148,   148,   148,   148,   148,
     148,   -40,     5,   148,   -40,   148,     9,   175,   186,   230,
       2,    -5,   -40,   -40,   -40,   111,   111,    89,   230,    -2,
       6,   -40,   -40,   -40,     1,    10,   -40,   141,   141,   148,
     148,    13,   -40,    19,   -40,    40,    25,   197,     5,   -40,
     141,   148,    28,    29,   -40,    30,   -40,   -40,   141,   110,
     -40,   -40
  };

  const unsigned char
  parser::yydefact_[] =
  {
       2,     0,     1,     0,     0,     0,     0,     0,     0,    38,
      40,    39,     5,    17,     0,     0,     0,     3,     0,     4,
      32,    31,    33,     0,    32,     8,     0,     0,    34,     0,
       0,     0,    29,    30,     0,     0,     0,     0,     0,     0,
       0,     6,     0,    34,     7,    34,     0,     0,     0,    35,
       0,     0,    11,    18,    23,    26,    27,    28,    24,    21,
      19,    20,    37,    25,     0,     0,     9,     0,     0,    34,
       0,    22,    22,     0,    14,    12,     0,     0,     0,    10,
       0,    34,     0,     0,    13,     0,    16,    17,     0,     0,
      15,    36
  };

  const signed char
  parser::yypgoto_[] =
  {
     -40,   -40,    -1,   -40,   -40,   -31,     0,   -39,   -40,   -16,
      62,   -40,   -40
  };

  const signed char
  parser::yydefgoto_[] =
  {
      -1,     1,    53,    46,    73,    30,    18,    50,    19,    63,
      24,    21,    22
  };

  const unsigned char
  parser::yytable_[] =
  {
      17,    25,    42,    23,    64,    26,    65,    29,    42,    34,
      35,    36,    43,    27,    31,    32,    33,    38,    45,    39,
      28,    51,    62,    40,    66,    70,    47,    48,    49,    69,
      76,    40,    71,    78,    55,    56,    57,    58,    59,    60,
      61,    72,    85,    49,     2,    49,    79,     3,    80,     4,
       5,     6,    81,     7,     8,    86,    89,    87,     9,    10,
      11,    88,    83,    20,     0,     0,    74,    75,     0,    49,
      77,    12,    13,     0,    14,     0,    15,    16,     0,    84,
       0,    49,     3,     0,     4,     5,     6,    90,     7,     8,
       0,     0,     0,     9,    10,    11,     0,     0,     0,     0,
      34,    35,    36,     0,     0,     0,    12,    13,    52,    14,
      39,    15,    16,     3,    40,     4,     5,     6,     0,     7,
       8,     0,    34,    35,     9,    10,    11,     0,     0,     0,
       0,     0,    39,     0,     0,     0,    40,    12,    13,    91,
      14,     0,    15,    16,     3,     0,     4,     5,     6,     0,
       7,     8,     0,     0,     0,     9,    10,    11,     0,     0,
       0,     0,     9,    10,    11,     0,     0,     0,    12,    13,
       0,    14,     0,    15,    16,    34,    35,    36,    14,     0,
      15,    16,    37,    38,     0,    39,    34,    35,    36,    40,
       0,     0,     0,    37,    38,    54,    39,    34,    35,    36,
      40,     0,     0,     0,    37,    38,    67,    39,    34,    35,
      36,    40,     0,     0,     0,    37,    38,    68,    39,    34,
      35,    36,    40,     0,     0,     0,    37,    38,    82,    39,
      34,    35,    36,    40,     0,    41,     0,    37,    38,     0,
      39,    34,    35,    36,    40,     0,    44,     0,    37,    38,
       0,    39,     0,     0,     0,    40
  };

  const signed char
  parser::yycheck_[] =
  {
       1,    28,    20,     3,    43,    30,    45,     8,    20,    11,
      12,    13,    30,    30,    14,    15,    16,    19,    30,    21,
      30,     6,    17,    25,    15,    30,    26,    27,    28,    27,
      69,    25,    31,    20,    34,    35,    36,    37,    38,    39,
      40,    31,    81,    43,     0,    45,    27,     3,     8,     5,
       6,     7,    27,     9,    10,    27,    87,    28,    14,    15,
      16,    31,    78,     1,    -1,    -1,    67,    68,    -1,    69,
      70,    27,    28,    -1,    30,    -1,    32,    33,    -1,    80,
      -1,    81,     3,    -1,     5,     6,     7,    88,     9,    10,
      -1,    -1,    -1,    14,    15,    16,    -1,    -1,    -1,    -1,
      11,    12,    13,    -1,    -1,    -1,    27,    28,    29,    30,
      21,    32,    33,     3,    25,     5,     6,     7,    -1,     9,
      10,    -1,    11,    12,    14,    15,    16,    -1,    -1,    -1,
      -1,    -1,    21,    -1,    -1,    -1,    25,    27,    28,    29,
      30,    -1,    32,    33,     3,    -1,     5,     6,     7,    -1,
       9,    10,    -1,    -1,    -1,    14,    15,    16,    -1,    -1,
      -1,    -1,    14,    15,    16,    -1,    -1,    -1,    27,    28,
      -1,    30,    -1,    32,    33,    11,    12,    13,    30,    -1,
      32,    33,    18,    19,    -1,    21,    11,    12,    13,    25,
      -1,    -1,    -1,    18,    19,    31,    21,    11,    12,    13,
      25,    -1,    -1,    -1,    18,    19,    31,    21,    11,    12,
      13,    25,    -1,    -1,    -1,    18,    19,    31,    21,    11,
      12,    13,    25,    -1,    -1,    -1,    18,    19,    31,    21,
      11,    12,    13,    25,    -1,    27,    -1,    18,    19,    -1,
      21,    11,    12,    13,    25,    -1,    27,    -1,    18,    19,
      -1,    21,    -1,    -1,    -1,    25
  };

  const unsigned char
  parser::yystos_[] =
  {
       0,    35,     0,     3,     5,     6,     7,     9,    10,    14,
      15,    16,    27,    28,    30,    32,    33,    36,    40,    42,
      44,    45,    46,    40,    44,    28,    30,    30,    30,    36,
      39,    40,    40,    40,    11,    12,    13,    18,    19,    21,
      25,    27,    20,    30,    27,    30,    37,    40,    40,    40,
      41,     6,    29,    36,    31,    40,    40,    40,    40,    40,
      40,    40,    17,    43,    41,    41,    15,    31,    31,    27,
      30,    31,    31,    38,    36,    36,    41,    40,    20,    27,
       8,    27,    31,    43,    36,    41,    27,    28,    31,    39,
      36,    29
  };

  const unsigned char
  parser::yyr1_[] =
  {
       0,    34,    35,    35,    35,    36,    36,    36,    37,    38,
      36,    36,    36,    36,    36,    36,    36,    39,    39,    40,
      40,    40,    40,    40,    40,    40,    40,    40,    40,    40,
      40,    40,    40,    40,    41,    41,    42,    43,    44,    45,
      46
  };

  const unsigned char
  parser::yyr2_[] =
  {
       0,     2,     0,     2,     2,     1,     2,     3,     0,     0,
       6,     3,     5,     7,     5,     9,     7,     0,     2,     3,
       3,     3,     4,     3,     3,     3,     3,     3,     3,     2,
       2,     1,     1,     1,     0,     1,     9,     1,     1,     1,
       1
  };



  // YYTNAME[SYMBOL-NUM] -- String name of the symbol SYMBOL-NUM.
  // First, the terminals, then, starting at \a yyntokens_, nonterminals.
  const char*
  const parser::yytname_[] =
  {
  "END_OF_FILE", "error", "$undefined", "RETURN", "INCLUDE", "ASM",
  "WHILE", "IF", "ELSE", "FOR", "DO", "\"==\"", "\"<=\"", "\"&&\"",
  "IDENTIFIER", "STRING", "LITERAL", "TYPE", "','", "'='", "':'", "'+'",
  "'-'", "'*'", "'/'", "'%'", "'~'", "';'", "'{'", "'}'", "'('", "')'",
  "'&'", "'@'", "$accept", "program", "statement", "$@1", "$@2",
  "compound_statement", "expression", "expression_or_nothing",
  "function_definition", "type", "identifier", "literal", "string_literal", YY_NULLPTR
  };

#if YYDEBUG
  const unsigned char
  parser::yyrline_[] =
  {
       0,    73,    73,    74,    75,    79,    80,    81,    82,    82,
      82,    83,    84,    85,    86,    87,    88,    92,    93,    97,
      98,    99,   100,   101,   102,   103,   104,   105,   106,   107,
     108,   109,   110,   111,   115,   116,   120,   124,   128,   132,
     136
  };

  // Print the state stack on the debug stream.
  void
  parser::yystack_print_ ()
  {
    *yycdebug_ << "Stack now";
    for (stack_type::const_iterator
           i = yystack_.begin (),
           i_end = yystack_.end ();
         i != i_end; ++i)
      *yycdebug_ << ' ' << i->state;
    *yycdebug_ << '\n';
  }

  // Report on the debug stream that the rule \a yyrule is going to be reduced.
  void
  parser::yy_reduce_print_ (int yyrule)
  {
    unsigned yylno = yyrline_[yyrule];
    int yynrhs = yyr2_[yyrule];
    // Print the symbols being reduced, and their result.
    *yycdebug_ << "Reducing stack by rule " << yyrule - 1
               << " (line " << yylno << "):\n";
    // The symbols being reduced.
    for (int yyi = 0; yyi < yynrhs; yyi++)
      YY_SYMBOL_PRINT ("   $" << yyi + 1 << " =",
                       yystack_[(yynrhs) - (yyi + 1)]);
  }
#endif // YYDEBUG


} //  cyy 



const static std::unordered_map<char, char> ESCAPE_SEQUENCES = {
	{ 'a', '\a' },
	{ 'b', '\b' },
	{ 'f', '\f' },
	{ 'n', '\n' },
	{ 'r', '\r' },
	{ 't', '\t' },
	{ 'v', '\v' },
	{ '\\', '\\' },
	{ '\'', '\'' },
	{ '\"', '\"' },
};

static std::string lexStringLiteral(kasm::CompoundInputFileStream& in)
{
	std::string str;

	std::streampos mar;
	for (;;)
	{
		
{
	char yych;
	yych = in.peek();
	switch (yych) {
	case '\n':	goto yy4;
	case '"':	goto yy6;
	case '\\':	goto yy8;
	default:	goto yy2;
	}
yy2:
	do { in.ignore(); if (in.eof()) throw std::runtime_error("Unclosed string"); } while(0);
	{ str.push_back(yych); continue; }
yy4:
	do { in.ignore(); if (in.eof()) throw std::runtime_error("Unclosed string"); } while(0);
	{ throw std::runtime_error("Unclosed string"); }
yy6:
	do { in.ignore(); if (in.eof()) throw std::runtime_error("Unclosed string"); } while(0);
	{ break; }
yy8:
	do { in.ignore(); if (in.eof()) throw std::runtime_error("Unclosed string"); } while(0);
	yych = in.peek();
	switch (yych) {
	case '"':
	case '\'':
	case '\\':
	case 'a':
	case 'b':
	case 'f':
	case 'n':
	case 'r':
	case 't':
	case 'v':	goto yy10;
	default:	goto yy9;
	}
yy9:
	{ throw std::runtime_error("Illegal escape character in string"); }
yy10:
	do { in.ignore(); if (in.eof()) throw std::runtime_error("Unclosed string"); } while(0);
	{ str.push_back('\\'); str.push_back(yych); continue; }
}

	}

	return str;
}

static std::string blockAsString(kasm::CompoundInputFileStream& in)
{
	std::string str;
	
	char c;
	for (;;)
	{
		in.get(c);
		if (c == '}') break;
		str.push_back(c);
	}

	return str;
}

static std::string getString(kasm::CompoundInputFileStream& in, std::streampos start, std::streampos end)
{
	std::string buffer;
	buffer.resize(end - start);
	in.seekg(start);
	in.read(buffer.data(), end - start);
	return buffer;
}

static char getChar(kasm::CompoundInputFileStream& in, std::streampos start, std::streampos end)
{
	in.seekg(start);
	char c;
	in.get(c);
	in.seekg(end);
	return c;
}

#define GET_STRING() getString(compiler.in, s, e)
#define GET_CHAR() getChar(compiler.in, s, e)

cyy::parser::symbol_type cyy::yylex(kasm::Compiler& compiler)
{
    std::streampos mar, s, e;
    std::streampos yyt1;

#define TOKEN(name) do { return parser::make_##name(compiler.loc); } while(0)
#define TOKENV(name, ...) do { return parser::make_##name(__VA_ARGS__, compiler.loc); } while(0)

	switch (compiler.parseFlag)
	{
	case kasm::Compiler::ParseFlag::BLOCK_AS_STRING:
		TOKENV(STRING, blockAsString(compiler.in));
		break;
	default:
		break;
	}

	for (;;)
	{
		
{
	char yych;
	unsigned int yyaccept = 0;
	mar = compiler.in.tellg();
	yych = compiler.in.peek();
	switch (yych) {
	case 0x08:
	case '\t':
	case '\v':
	case '\f':
	case ' ':	goto yy15;
	case '\n':	goto yy17;
	case '\r':	goto yy19;
	case '"':	goto yy20;
	case '%':	goto yy22;
	case '&':	goto yy24;
	case '\'':	goto yy25;
	case '(':
	case ')':
	case '*':
	case ',':
	case '.':
	case ':':
	case ';':
	case '>':
	case '?':
	case '@':
	case '{':
	case '|':
	case '}':
	case '~':	goto yy27;
	case '+':
	case '-':
		yyt1 = compiler.in.eof() ? std::streampos(0) : compiler.in.tellg();
		goto yy28;
	case '/':
		yyt1 = compiler.in.eof() ? std::streampos(0) : compiler.in.tellg();
		goto yy29;
	case '0':
		yyt1 = compiler.in.eof() ? std::streampos(0) : compiler.in.tellg();
		goto yy30;
	case '1':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
		yyt1 = compiler.in.eof() ? std::streampos(0) : compiler.in.tellg();
		goto yy32;
	case '2':
		yyt1 = compiler.in.eof() ? std::streampos(0) : compiler.in.tellg();
		goto yy34;
	case '<':	goto yy35;
	case '=':	goto yy36;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'b':
	case 'c':
	case 'g':
	case 'h':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'x':
	case 'y':
	case 'z':
		yyt1 = compiler.in.eof() ? std::streampos(0) : compiler.in.tellg();
		goto yy37;
	case 'a':
		yyt1 = compiler.in.eof() ? std::streampos(0) : compiler.in.tellg();
		goto yy40;
	case 'd':
		yyt1 = compiler.in.eof() ? std::streampos(0) : compiler.in.tellg();
		goto yy41;
	case 'e':
		yyt1 = compiler.in.eof() ? std::streampos(0) : compiler.in.tellg();
		goto yy42;
	case 'f':
		yyt1 = compiler.in.eof() ? std::streampos(0) : compiler.in.tellg();
		goto yy43;
	case 'i':
		yyt1 = compiler.in.eof() ? std::streampos(0) : compiler.in.tellg();
		goto yy44;
	case 'r':
		yyt1 = compiler.in.eof() ? std::streampos(0) : compiler.in.tellg();
		goto yy45;
	case 's':
		yyt1 = compiler.in.eof() ? std::streampos(0) : compiler.in.tellg();
		goto yy46;
	case 't':
		yyt1 = compiler.in.eof() ? std::streampos(0) : compiler.in.tellg();
		goto yy47;
	case 'u':
		yyt1 = compiler.in.eof() ? std::streampos(0) : compiler.in.tellg();
		goto yy48;
	case 'v':
		yyt1 = compiler.in.eof() ? std::streampos(0) : compiler.in.tellg();
		goto yy49;
	case 'w':
		yyt1 = compiler.in.eof() ? std::streampos(0) : compiler.in.tellg();
		goto yy50;
	default:
		yyt1 = compiler.in.eof() ? std::streampos(0) : compiler.in.tellg();
		goto yy14;
	}
yy14:
	s = yyt1;
	e = compiler.in.eof() ? std::streampos(0) : compiler.in.tellg();
	{ throw std::runtime_error(std::string("Invalid character of value: " + std::to_string(GET_CHAR())).c_str()); }
yy15:
	do { compiler.in.ignore(); if (compiler.in.eof()) TOKEN(END_OF_FILE); } while(0);
	{ compiler.loc.columns(); continue; }
yy17:
	do { compiler.in.ignore(); if (compiler.in.eof()) TOKEN(END_OF_FILE); } while(0);
yy18:
	{ compiler.loc.lines(); compiler.loc.step(); continue; }
yy19:
	do { compiler.in.ignore(); if (compiler.in.eof()) TOKEN(END_OF_FILE); } while(0);
	yych = compiler.in.peek();
	switch (yych) {
	case '\n':	goto yy17;
	default:	goto yy18;
	}
yy20:
	do { compiler.in.ignore(); if (compiler.in.eof()) TOKEN(END_OF_FILE); } while(0);
	{ TOKENV(STRING, lexStringLiteral(compiler.in)); }
yy22:
	yyaccept = 1;
	do { compiler.in.ignore(); if (compiler.in.eof()) TOKEN(END_OF_FILE); } while(0);
	mar = compiler.in.tellg();
	yych = compiler.in.peek();
	switch (yych) {
	case 'i':	goto yy51;
	default:	goto yy23;
	}
yy23:
	s = compiler.in.eof() ? std::streampos(0) : compiler.in.tellg();
	s += -1;
	e = compiler.in.eof() ? std::streampos(0) : compiler.in.tellg();
	{ return parser::symbol_type(parser::token_type(GET_CHAR()), compiler.loc); }
yy24:
	do { compiler.in.ignore(); if (compiler.in.eof()) TOKEN(END_OF_FILE); } while(0);
	yych = compiler.in.peek();
	switch (yych) {
	case '&':	goto yy52;
	default:	goto yy23;
	}
yy25:
	do { compiler.in.ignore(); if (compiler.in.eof()) TOKEN(END_OF_FILE); } while(0);
	yych = compiler.in.peek();
	switch (yych) {
	case '"':
	case '\'':	goto yy26;
	case '\\':	goto yy55;
	default:	goto yy54;
	}
yy26:
	compiler.in.seekg(mar);
	switch (yyaccept) {
	case 0:
		yyt1 = compiler.in.eof() ? std::streampos(0) : compiler.in.tellg();
		goto yy14;
	case 1:
		goto yy23;
	default:
		goto yy31;
	}
yy27:
	do { compiler.in.ignore(); if (compiler.in.eof()) TOKEN(END_OF_FILE); } while(0);
	goto yy23;
yy28:
	do { compiler.in.ignore(); if (compiler.in.eof()) TOKEN(END_OF_FILE); } while(0);
	yych = compiler.in.peek();
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy32;
	default:	goto yy23;
	}
yy29:
	do { compiler.in.ignore(); if (compiler.in.eof()) TOKEN(END_OF_FILE); } while(0);
	yych = compiler.in.peek();
	switch (yych) {
	case '/':	goto yy56;
	default:	goto yy23;
	}
yy30:
	yyaccept = 2;
	do { compiler.in.ignore(); if (compiler.in.eof()) TOKEN(END_OF_FILE); } while(0);
	mar = compiler.in.tellg();
	yych = compiler.in.peek();
	switch (yych) {
	case 'b':	goto yy59;
	case 'x':	goto yy60;
	default:	goto yy33;
	}
yy31:
	s = yyt1;
	e = compiler.in.eof() ? std::streampos(0) : compiler.in.tellg();
	{ TOKENV(LITERAL, std::stoi(GET_STRING(), nullptr, 10)); }
yy32:
	do { compiler.in.ignore(); if (compiler.in.eof()) TOKEN(END_OF_FILE); } while(0);
	yych = compiler.in.peek();
yy33:
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy32;
	default:	goto yy31;
	}
yy34:
	do { compiler.in.ignore(); if (compiler.in.eof()) TOKEN(END_OF_FILE); } while(0);
	yych = compiler.in.peek();
	switch (yych) {
	case '8':	goto yy61;
	default:	goto yy33;
	}
yy35:
	do { compiler.in.ignore(); if (compiler.in.eof()) TOKEN(END_OF_FILE); } while(0);
	yych = compiler.in.peek();
	switch (yych) {
	case '=':	goto yy63;
	default:	goto yy23;
	}
yy36:
	do { compiler.in.ignore(); if (compiler.in.eof()) TOKEN(END_OF_FILE); } while(0);
	yych = compiler.in.peek();
	switch (yych) {
	case '=':	goto yy65;
	default:	goto yy23;
	}
yy37:
	do { compiler.in.ignore(); if (compiler.in.eof()) TOKEN(END_OF_FILE); } while(0);
	yych = compiler.in.peek();
yy38:
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy37;
	default:	goto yy39;
	}
yy39:
	s = yyt1;
	e = compiler.in.eof() ? std::streampos(0) : compiler.in.tellg();
	{ TOKENV(IDENTIFIER, GET_STRING()); }
yy40:
	do { compiler.in.ignore(); if (compiler.in.eof()) TOKEN(END_OF_FILE); } while(0);
	yych = compiler.in.peek();
	switch (yych) {
	case 's':	goto yy67;
	default:	goto yy38;
	}
yy41:
	do { compiler.in.ignore(); if (compiler.in.eof()) TOKEN(END_OF_FILE); } while(0);
	yych = compiler.in.peek();
	switch (yych) {
	case 'o':	goto yy68;
	default:	goto yy38;
	}
yy42:
	do { compiler.in.ignore(); if (compiler.in.eof()) TOKEN(END_OF_FILE); } while(0);
	yych = compiler.in.peek();
	switch (yych) {
	case 'l':	goto yy70;
	default:	goto yy38;
	}
yy43:
	do { compiler.in.ignore(); if (compiler.in.eof()) TOKEN(END_OF_FILE); } while(0);
	yych = compiler.in.peek();
	switch (yych) {
	case 'o':	goto yy71;
	default:	goto yy38;
	}
yy44:
	do { compiler.in.ignore(); if (compiler.in.eof()) TOKEN(END_OF_FILE); } while(0);
	yych = compiler.in.peek();
	switch (yych) {
	case 'f':	goto yy72;
	default:	goto yy38;
	}
yy45:
	do { compiler.in.ignore(); if (compiler.in.eof()) TOKEN(END_OF_FILE); } while(0);
	yych = compiler.in.peek();
	switch (yych) {
	case 'e':	goto yy74;
	default:	goto yy38;
	}
yy46:
	do { compiler.in.ignore(); if (compiler.in.eof()) TOKEN(END_OF_FILE); } while(0);
	yych = compiler.in.peek();
	switch (yych) {
	case '3':	goto yy75;
	default:	goto yy38;
	}
yy47:
	do { compiler.in.ignore(); if (compiler.in.eof()) TOKEN(END_OF_FILE); } while(0);
	yych = compiler.in.peek();
	switch (yych) {
	case 'y':	goto yy76;
	default:	goto yy38;
	}
yy48:
	do { compiler.in.ignore(); if (compiler.in.eof()) TOKEN(END_OF_FILE); } while(0);
	yych = compiler.in.peek();
	switch (yych) {
	case '3':	goto yy77;
	case '8':	goto yy78;
	default:	goto yy38;
	}
yy49:
	do { compiler.in.ignore(); if (compiler.in.eof()) TOKEN(END_OF_FILE); } while(0);
	yych = compiler.in.peek();
	switch (yych) {
	case 'o':	goto yy80;
	default:	goto yy38;
	}
yy50:
	do { compiler.in.ignore(); if (compiler.in.eof()) TOKEN(END_OF_FILE); } while(0);
	yych = compiler.in.peek();
	switch (yych) {
	case 'h':	goto yy81;
	default:	goto yy38;
	}
yy51:
	do { compiler.in.ignore(); if (compiler.in.eof()) TOKEN(END_OF_FILE); } while(0);
	yych = compiler.in.peek();
	switch (yych) {
	case 'n':	goto yy82;
	default:	goto yy26;
	}
yy52:
	do { compiler.in.ignore(); if (compiler.in.eof()) TOKEN(END_OF_FILE); } while(0);
	{ TOKEN(LOGICAL_AND); }
yy54:
	do { compiler.in.ignore(); if (compiler.in.eof()) TOKEN(END_OF_FILE); } while(0);
	yych = compiler.in.peek();
	switch (yych) {
	case '\'':	goto yy83;
	default:	goto yy26;
	}
yy55:
	do { compiler.in.ignore(); if (compiler.in.eof()) TOKEN(END_OF_FILE); } while(0);
	yych = compiler.in.peek();
	switch (yych) {
	case '\n':	goto yy26;
	default:	goto yy85;
	}
yy56:
	do { compiler.in.ignore(); if (compiler.in.eof()) TOKEN(END_OF_FILE); } while(0);
	yych = compiler.in.peek();
	switch (yych) {
	case '\n':
	case '\r':	goto yy58;
	default:	goto yy56;
	}
yy58:
	s = yyt1;
	e = compiler.in.eof() ? std::streampos(0) : compiler.in.tellg();
	{ continue; }
yy59:
	do { compiler.in.ignore(); if (compiler.in.eof()) TOKEN(END_OF_FILE); } while(0);
	yych = compiler.in.peek();
	switch (yych) {
	case '0':
	case '1':	goto yy86;
	default:	goto yy26;
	}
yy60:
	do { compiler.in.ignore(); if (compiler.in.eof()) TOKEN(END_OF_FILE); } while(0);
	yych = compiler.in.peek();
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy89;
	default:	goto yy26;
	}
yy61:
	do { compiler.in.ignore(); if (compiler.in.eof()) TOKEN(END_OF_FILE); } while(0);
	yych = compiler.in.peek();
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy32;
	default:	goto yy62;
	}
yy62:
	{ TOKENV(TYPE, kasm::ast::Type::S8); }
yy63:
	do { compiler.in.ignore(); if (compiler.in.eof()) TOKEN(END_OF_FILE); } while(0);
	{ TOKEN(LESS_THAN_OR_EQUAL); }
yy65:
	do { compiler.in.ignore(); if (compiler.in.eof()) TOKEN(END_OF_FILE); } while(0);
	{ TOKEN(EQUAL); }
yy67:
	do { compiler.in.ignore(); if (compiler.in.eof()) TOKEN(END_OF_FILE); } while(0);
	yych = compiler.in.peek();
	switch (yych) {
	case 'm':	goto yy92;
	default:	goto yy38;
	}
yy68:
	do { compiler.in.ignore(); if (compiler.in.eof()) TOKEN(END_OF_FILE); } while(0);
	yych = compiler.in.peek();
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy37;
	default:	goto yy69;
	}
yy69:
	{ TOKEN(DO); }
yy70:
	do { compiler.in.ignore(); if (compiler.in.eof()) TOKEN(END_OF_FILE); } while(0);
	yych = compiler.in.peek();
	switch (yych) {
	case 's':	goto yy94;
	default:	goto yy38;
	}
yy71:
	do { compiler.in.ignore(); if (compiler.in.eof()) TOKEN(END_OF_FILE); } while(0);
	yych = compiler.in.peek();
	switch (yych) {
	case 'r':	goto yy95;
	default:	goto yy38;
	}
yy72:
	do { compiler.in.ignore(); if (compiler.in.eof()) TOKEN(END_OF_FILE); } while(0);
	yych = compiler.in.peek();
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy37;
	default:	goto yy73;
	}
yy73:
	{ TOKEN(IF); }
yy74:
	do { compiler.in.ignore(); if (compiler.in.eof()) TOKEN(END_OF_FILE); } while(0);
	yych = compiler.in.peek();
	switch (yych) {
	case 't':	goto yy97;
	default:	goto yy38;
	}
yy75:
	do { compiler.in.ignore(); if (compiler.in.eof()) TOKEN(END_OF_FILE); } while(0);
	yych = compiler.in.peek();
	switch (yych) {
	case '2':	goto yy98;
	default:	goto yy38;
	}
yy76:
	do { compiler.in.ignore(); if (compiler.in.eof()) TOKEN(END_OF_FILE); } while(0);
	yych = compiler.in.peek();
	switch (yych) {
	case 'p':	goto yy100;
	default:	goto yy38;
	}
yy77:
	do { compiler.in.ignore(); if (compiler.in.eof()) TOKEN(END_OF_FILE); } while(0);
	yych = compiler.in.peek();
	switch (yych) {
	case '2':	goto yy101;
	default:	goto yy38;
	}
yy78:
	do { compiler.in.ignore(); if (compiler.in.eof()) TOKEN(END_OF_FILE); } while(0);
	yych = compiler.in.peek();
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy37;
	default:	goto yy79;
	}
yy79:
	{ TOKENV(TYPE, kasm::ast::Type::U8); }
yy80:
	do { compiler.in.ignore(); if (compiler.in.eof()) TOKEN(END_OF_FILE); } while(0);
	yych = compiler.in.peek();
	switch (yych) {
	case 'i':	goto yy103;
	default:	goto yy38;
	}
yy81:
	do { compiler.in.ignore(); if (compiler.in.eof()) TOKEN(END_OF_FILE); } while(0);
	yych = compiler.in.peek();
	switch (yych) {
	case 'i':	goto yy104;
	default:	goto yy38;
	}
yy82:
	do { compiler.in.ignore(); if (compiler.in.eof()) TOKEN(END_OF_FILE); } while(0);
	yych = compiler.in.peek();
	switch (yych) {
	case 'c':	goto yy105;
	default:	goto yy26;
	}
yy83:
	do { compiler.in.ignore(); if (compiler.in.eof()) TOKEN(END_OF_FILE); } while(0);
	s = compiler.in.eof() ? std::streampos(0) : compiler.in.tellg();
	s += -2;
	e = compiler.in.eof() ? std::streampos(0) : compiler.in.tellg();
	{ TOKENV(LITERAL, GET_CHAR()); }
yy85:
	do { compiler.in.ignore(); if (compiler.in.eof()) TOKEN(END_OF_FILE); } while(0);
	yych = compiler.in.peek();
	switch (yych) {
	case '\'':	goto yy106;
	default:	goto yy26;
	}
yy86:
	do { compiler.in.ignore(); if (compiler.in.eof()) TOKEN(END_OF_FILE); } while(0);
	yych = compiler.in.peek();
	switch (yych) {
	case '0':
	case '1':	goto yy86;
	default:	goto yy88;
	}
yy88:
	s = yyt1;
	e = compiler.in.eof() ? std::streampos(0) : compiler.in.tellg();
	{ TOKENV(LITERAL, std::stoi(GET_STRING(), nullptr, 2)); }
yy89:
	do { compiler.in.ignore(); if (compiler.in.eof()) TOKEN(END_OF_FILE); } while(0);
	yych = compiler.in.peek();
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy89;
	default:	goto yy91;
	}
yy91:
	s = yyt1;
	e = compiler.in.eof() ? std::streampos(0) : compiler.in.tellg();
	{ TOKENV(LITERAL, std::stoi(GET_STRING(), nullptr, 16)); }
yy92:
	do { compiler.in.ignore(); if (compiler.in.eof()) TOKEN(END_OF_FILE); } while(0);
	yych = compiler.in.peek();
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy37;
	default:	goto yy93;
	}
yy93:
	{ TOKEN(ASM); }
yy94:
	do { compiler.in.ignore(); if (compiler.in.eof()) TOKEN(END_OF_FILE); } while(0);
	yych = compiler.in.peek();
	switch (yych) {
	case 'e':	goto yy108;
	default:	goto yy38;
	}
yy95:
	do { compiler.in.ignore(); if (compiler.in.eof()) TOKEN(END_OF_FILE); } while(0);
	yych = compiler.in.peek();
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy37;
	default:	goto yy96;
	}
yy96:
	{ TOKEN(FOR); }
yy97:
	do { compiler.in.ignore(); if (compiler.in.eof()) TOKEN(END_OF_FILE); } while(0);
	yych = compiler.in.peek();
	switch (yych) {
	case 'u':	goto yy110;
	default:	goto yy38;
	}
yy98:
	do { compiler.in.ignore(); if (compiler.in.eof()) TOKEN(END_OF_FILE); } while(0);
	yych = compiler.in.peek();
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy37;
	default:	goto yy99;
	}
yy99:
	{ TOKENV(TYPE, kasm::ast::Type::S32); }
yy100:
	do { compiler.in.ignore(); if (compiler.in.eof()) TOKEN(END_OF_FILE); } while(0);
	yych = compiler.in.peek();
	switch (yych) {
	case 'e':	goto yy111;
	default:	goto yy38;
	}
yy101:
	do { compiler.in.ignore(); if (compiler.in.eof()) TOKEN(END_OF_FILE); } while(0);
	yych = compiler.in.peek();
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy37;
	default:	goto yy102;
	}
yy102:
	{ TOKENV(TYPE, kasm::ast::Type::U32); }
yy103:
	do { compiler.in.ignore(); if (compiler.in.eof()) TOKEN(END_OF_FILE); } while(0);
	yych = compiler.in.peek();
	switch (yych) {
	case 'd':	goto yy113;
	default:	goto yy38;
	}
yy104:
	do { compiler.in.ignore(); if (compiler.in.eof()) TOKEN(END_OF_FILE); } while(0);
	yych = compiler.in.peek();
	switch (yych) {
	case 'l':	goto yy115;
	default:	goto yy38;
	}
yy105:
	do { compiler.in.ignore(); if (compiler.in.eof()) TOKEN(END_OF_FILE); } while(0);
	yych = compiler.in.peek();
	switch (yych) {
	case 'l':	goto yy116;
	default:	goto yy26;
	}
yy106:
	do { compiler.in.ignore(); if (compiler.in.eof()) TOKEN(END_OF_FILE); } while(0);
	s = compiler.in.eof() ? std::streampos(0) : compiler.in.tellg();
	s += -2;
	e = compiler.in.eof() ? std::streampos(0) : compiler.in.tellg();
	{ TOKENV(LITERAL, ESCAPE_SEQUENCES.at(GET_CHAR())); }
yy108:
	do { compiler.in.ignore(); if (compiler.in.eof()) TOKEN(END_OF_FILE); } while(0);
	yych = compiler.in.peek();
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy37;
	default:	goto yy109;
	}
yy109:
	{ TOKEN(ELSE); }
yy110:
	do { compiler.in.ignore(); if (compiler.in.eof()) TOKEN(END_OF_FILE); } while(0);
	yych = compiler.in.peek();
	switch (yych) {
	case 'r':	goto yy117;
	default:	goto yy38;
	}
yy111:
	do { compiler.in.ignore(); if (compiler.in.eof()) TOKEN(END_OF_FILE); } while(0);
	yych = compiler.in.peek();
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy37;
	default:	goto yy112;
	}
yy112:
	{ TOKENV(TYPE, kasm::ast::Type::TYPE); }
yy113:
	do { compiler.in.ignore(); if (compiler.in.eof()) TOKEN(END_OF_FILE); } while(0);
	yych = compiler.in.peek();
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy37;
	default:	goto yy114;
	}
yy114:
	{ TOKENV(TYPE, kasm::ast::Type::VOID); }
yy115:
	do { compiler.in.ignore(); if (compiler.in.eof()) TOKEN(END_OF_FILE); } while(0);
	yych = compiler.in.peek();
	switch (yych) {
	case 'e':	goto yy118;
	default:	goto yy38;
	}
yy116:
	do { compiler.in.ignore(); if (compiler.in.eof()) TOKEN(END_OF_FILE); } while(0);
	yych = compiler.in.peek();
	switch (yych) {
	case 'u':	goto yy120;
	default:	goto yy26;
	}
yy117:
	do { compiler.in.ignore(); if (compiler.in.eof()) TOKEN(END_OF_FILE); } while(0);
	yych = compiler.in.peek();
	switch (yych) {
	case 'n':	goto yy121;
	default:	goto yy38;
	}
yy118:
	do { compiler.in.ignore(); if (compiler.in.eof()) TOKEN(END_OF_FILE); } while(0);
	yych = compiler.in.peek();
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy37;
	default:	goto yy119;
	}
yy119:
	{ TOKEN(WHILE); }
yy120:
	do { compiler.in.ignore(); if (compiler.in.eof()) TOKEN(END_OF_FILE); } while(0);
	yych = compiler.in.peek();
	switch (yych) {
	case 'd':	goto yy123;
	default:	goto yy26;
	}
yy121:
	do { compiler.in.ignore(); if (compiler.in.eof()) TOKEN(END_OF_FILE); } while(0);
	yych = compiler.in.peek();
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy37;
	default:	goto yy122;
	}
yy122:
	{ TOKEN(RETURN); }
yy123:
	do { compiler.in.ignore(); if (compiler.in.eof()) TOKEN(END_OF_FILE); } while(0);
	yych = compiler.in.peek();
	switch (yych) {
	case 'e':	goto yy124;
	default:	goto yy26;
	}
yy124:
	do { compiler.in.ignore(); if (compiler.in.eof()) TOKEN(END_OF_FILE); } while(0);
	{ TOKEN(INCLUDE); }
}

	}
}

void cyy::parser::error(const location_type& l, const std::string& message)
{
    std::cerr << l.begin.filename->c_str() << ':' << l.begin.line << ':' << l.begin.column << '-' << l.end.column << ": " << message << '\n';
}
